# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/olive/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/olive

# Inherit fragments
$(call inherit-product, vendor/xiaomi/olive/olive-vendor-acdb.mk)
$(call inherit-product, vendor/xiaomi/olive/olive-vendor-camera.mk)
$(call inherit-product, vendor/xiaomi/olive/olive-vendor-firmware.mk)