# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/olivelite/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/olivelite

# Inherit fragments
$(call inherit-product, vendor/xiaomi/olivelite/olivelite-vendor-acdb.mk)
$(call inherit-product, vendor/xiaomi/olivelite/olivelite-vendor-camera.mk)
$(call inherit-product, vendor/xiaomi/olivelite/olivelite-vendor-firmware.mk)